language: node_js

node_js:
  - 12.13.0

cache:
  directories:
  - "node_modules"

notifications:
  email:
    on_success: never

branches:
  only:
    - main

install:
  - yarn

script:
  scripts:
  - npm install codecov -g
  - yarn run test
  - yarn run build

after_success:
  - codecov