name: Exit pre-release mode

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Exit pre-release mode on beta release branch"
        type: string
        default: "beta/release-"
        required: true

jobs:
  exit_prerelease:
    name: exit pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0

      - name: Install
        uses: ./.github/common-actions/install

      - name: remove pre.json
        # we only remove .changeset/pre.json here 
        # since we want to keep the changeset files introduced in this beta/release-* branch
        # once we merge it to canary, those files will be removed in version PR in canary 
        # and converted to corresponding changelogs
        run: npx rimraf .changeset/pre.json

      - name: Commit and push changes
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git commit -m "ci(changesets): exit pre-release mode"
          git push