name: CI/CD

on:
  push:
    branches: [main]
    paths-ignore: ['**/README.md']
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore: ['**/README.md']

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build

  tests:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn coverage
      - uses: codecov/codecov-action@v2
        with:
          directory: './packages/nextui'
        
  publish:
    needs: [build, tests]
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './packages/nextui/package.json'

      - name: Show published version
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

  deploy:
    needs: [publish]
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          github-token: ${{ github.token }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-name: ${{ secrets.VERCEL_PROJECT_NAME}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} 
          working-directory: './packages/docs'

  update_algolia_index:
    needs: [publish]
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Upload docs on Algolia
        run: yarn build:docs-meta

          
